# Generated by Django 2.0.2 on 2018-04-21 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('subtitle', models.CharField(default='', max_length=100, verbose_name='文章副标题')),
                ('img', models.CharField(max_length=200, verbose_name='展示图片')),
                ('tags', models.CharField(help_text='填写Tag标识Id，多个用|分割', max_length=200, verbose_name='标签')),
                ('abstract', models.TextField(verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 4, 21, 13, 19, 48, 545630), verbose_name='创建日期')),
                ('modify_time', models.DateTimeField(default=datetime.datetime(2018, 4, 21, 13, 19, 48, 545630), verbose_name='修改日期')),
                ('praise_num', models.IntegerField(default=0, verbose_name='赞数量')),
                ('comments_num', models.IntegerField(default=0, verbose_name='评论数量')),
                ('browse_num', models.IntegerField(default=0, verbose_name='浏览数量')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=40, verbose_name='标签标识Id')),
                ('name', models.CharField(max_length=40, verbose_name='标签名称')),
                ('order', models.IntegerField(default=0, verbose_name='标签顺序')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=40, verbose_name='类型标识Id')),
                ('name', models.CharField(max_length=40, verbose_name='类型名称')),
                ('order', models.IntegerField(default=0, verbose_name='类型顺序')),
            ],
        ),
    ]
