# Generated by Django 2.0.2 on 2018-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('img', models.CharField(max_length=200, verbose_name='展示图片')),
                ('tags', models.CharField(help_text='多个用|分割', max_length=200, verbose_name='标签')),
                ('abstract', models.TextField(verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('create_time', models.IntegerField(default=0, verbose_name='创建日期')),
                ('praise_num', models.IntegerField(default=0, verbose_name='赞数量')),
                ('comments_num', models.IntegerField(default=0, verbose_name='评论数量')),
                ('browse_num', models.IntegerField(default=0, verbose_name='浏览数量')),
            ],
        ),
        migrations.CreateModel(
            name='BArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='类型名称')),
                ('order', models.IntegerField(default=0, verbose_name='类型顺序')),
            ],
        ),
    ]
